### ISSUE TITLE
[Get /history] 500 internal server error for the 1.0.0 safe

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway-nest#340]
**Request** : https://safe-client-nest.staging.5afe.dev/v1/chains/1/safes/0xcd2E72aEBe2A203b84f46DEEC948E6465dB51c75/transactions/history
**Response** : {statusCode: 500, message: "Internal server error"}
message: "Internal server error"
statusCode: 500

**Comment by fmrsabino** [comment]
One of the transactions of `/v1/chains/1/safes/0xcd2E72aEBe2A203b84f46DEEC948E6465dB51c75/transactions/history` is the following.

```json
{
  "type": "TRANSACTION",
  "transaction": {
    "id": "multisig_0xcd2E72aEBe2A203b84f46DEEC948E6465dB51c75_0x7be4bcda45005dd96f79f8c2b79a758d12209dfb85c42aa4d4feaa28d6a1aa2d",
    "timestamp": 1644280379000,
    "txStatus": "SUCCESS",
    "txInfo": {
      "type": "Custom",
      "to": {
        "value": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      },
      "dataSize": "68",
      "value": "0",
      "methodName": "transfer",
      "isCancellation": false
    },
    "executionInfo": {
      "type": "MULTISIG",
      "nonce": 41,
      "confirmationsRequired": 1,
      "confirmationsSubmitted": 1
    }
  },
  "conflictType": "None"
}
```

This transaction has the following `origin`: `https://gnosis-safe.io`

In the old implementation of the CGW (Rust) if there was an error parsing this field it would result in `null` and that's why there's no `safeAppInfo` in the payload above.

In the current implementation there's no such fallback... it expects `origin` to be in the format of `"origin": { "url": <url> }` resulting in a server error.
